### ISSUE TITLE
Animate pivot point

### ISSUE THREAD

**Issue by kevinvayro** [davidfig/pixi-ease#19]
Currently there doesn't seem to be a way to animate the pivot/anchor. Is this possible?

My initial thoughts are it's more difficult due to the pivot/anchor values being objects rather than just a number on the element being eased.

**Comment by davidfig** [comment]
You have to go one level deeper to get it working: `ease.add(sprite.pivot, { x: 100, y: 100 })`

**Comment by kevinvayro** [comment]
Perfect! That works. Thanks for the quick response.
