### ISSUE TITLE
How to stack multiple animations on same object in order

### ISSUE THREAD

**Issue by gapipro** [davidfig/pixi-ease#3]
So I can't really figure out how to solve this problem.

So for example we have a very simple animation.
Object is initially at position A, then it moves to position B, waits 2s, and moves from position B to position C.

How do I have to configure animation list to get animation like that? Currently it always starts animation B->C from position A instead of B.

**Comment by davidfig** [comment]
Here you go:

```js
ease = new Ease.list()

object.position.set(ax, bx)

ease.to(object, { x: bx, y: by }, time)
   .on('done', () => ease.to(object, { x: cx, y: cy }, time, { wait: 2000 }) )  
```
The problem you were having was that when you initialize an ease, it uses the current value as the starting point for the ease, even if you add a wait. So if you create a second animation with a wait = firstTime + waitingTime then when the second animation triggers, it uses the initial value of position A instead when calculating the ease. 

Creating the ease on the 'done' event fixes that problem.

Hope this helps!

**Comment by gapipro** [comment]
Ok yep. That works. Thank you.
