### ISSUE TITLE
Animations flicker after switching browser tabs.

### ISSUE THREAD

**Issue by ThatBrianDude** [davidfig/pixi-ease#4]
It seems like after I come back to the tab after a while, animations have been "queued up" and all play at once resulting in their state switching from (seemingly) start to finish 10 times a second.

A temporary workaround for me is to remove all animations once the browser tabs "blur" event is called and then readd them once "focus" is fired. This results in a "lifeless" game when losing focus on the window. It becomes alive again once focus comes back at least so I guess this is "acceptable".

Is this avoidable otherwise? I am pretty sure my implementation was nothing too specific: 

const animationList = new Ease.list()

animationList.to(graphic.scale, { x: 1.2,  y: 1.2 }, 500, { ease: "easeInSine", repeat: true, reverse: true })

**Comment by davidfig** [comment]
I noticed this too. Are you running in Chrome? This seems like a new behavior. I'll look into it.

**Comment by davidfig** [comment]
Try out v1.1.1. It uses a capped time per second (PIXI.ticker.deltaTime instead of elapsedMS). Let me know if you're still seeing flickering.

**Comment by ThatBrianDude** [comment]
No more flickering, awesome!
